In [1]:
import numpy as np

## Problem 5

In [10]:
def create_R_x(roll):
    roll = np.deg2rad(roll)
    R = np.array([
        [1, 0, 0],
        [0, np.cos(roll), -np.sin(roll)],
        [0, np.sin(roll), np.cos(roll)]
    ])
    return R

def create_R_y(pitch):
    pitch = np.deg2rad(pitch)
    R = np.array([
        [np.cos(pitch), 0, np.sin(pitch)],
        [0, 1, 0],
        [-np.sin(pitch), 0, np.cos(pitch)]
    ])
    return R

def create_R_z(yaw):
    yaw = np.deg2rad(yaw)
    R = np.array([
        [np.cos(yaw), -np.sin(yaw), 0],
        [np.sin(yaw), np.cos(yaw), 0],
        [0, 0, 1]
    ])
    return R

In [11]:
p = np.array([2, 0, 1]).reshape(3,1)

### a.

In [12]:
R_x0 = create_R_x(30)
R_y1 = create_R_y(60)
R_z2 = create_R_z(90)

R1 = R_z2 @ R_y1 @ R_x0
p1 = R1 @ p

In [13]:
p1

array([[ 0.5       ],
       [ 1.75      ],
       [-1.29903811]])

### b.

In [15]:
R_z0 = create_R_z(90)
R_y1 = create_R_y(60)
R_x2 = create_R_x(30)

R2 = R_x2 @ R_y1 @ R_z0
p2 = R2 @ p

In [16]:
p2

array([[0.8660254 ],
       [1.48205081],
       [1.4330127 ]])

## Problem 6

In [18]:
R_x0 = create_R_x(30)
R_y0 = create_R_y(60)
R_z0 = create_R_z(90)

R3 = R_z0 @ R_y0 @ R_x0
p3 = R3 @ p

In [19]:
p3

array([[ 0.5       ],
       [ 1.75      ],
       [-1.29903811]])